---
version: 1.0
gsf:
    basic:
        model_encoder_type: rgat
        backend: gloo
        verbose: false
    gnn:
        fanout: "50,50"
        num_layers: 2
        hidden_size: 256
        use_mini_batch_infer: false
        lp_decoder_type: DistMult
    input:
        restore_model_path: null
    output:
        save_model_path: /tmp/acm_nc/models
        save_embeds_path: /tmp/acm_nc/embeds
    hyperparam:
        dropout: 0.
        lr: 0.0001
        lm_tune_lr: 0.0001
        num_epochs: 20
        batch_size: 1024
        bert_infer_bs: 128
        wd_l2norm: 0
        alpha_l2norm: 0.
        num_ffn_layers_in_input: 2
        num_ffn_layers_in_gnn: 1
    rgat:
        num_heads: -1
        use_self_loop: true
        sparse_optimizer_lr: 1e-2
        use_node_embeddings: false
        lp_decoder_type: DistMult
    link_prediction:
        num_negative_edges: 10
        num_negative_edges_eval: 100
        train_negative_sampler: joint
        eval_etype:
            - "paper,citing,paper"
        train_etype:
            - "paper,citing,paper"
            - "author,writing,paper"
            - "paper,written-by,author"
        exclude_training_targets: false
        reverse_edge_types_map: ["paper,citing,cited,paper"]
